LIBPHLOX_SRC +=                   \
	$(LOCDIR)/arch_start.S    \
	$(LOCDIR)/arch_syscall.S

SERVICE_LDSCRIPT := $(LOCDIR)/service.ld

LIBPHLOX_ASFLAGS += $(GLOBAL_ASFLAGS) $(GLOBAL_CFLAGS) $(INCLUDES)
